# This is a basic workflow to help you get started with Actions

name: AppThreat/sast-scan-action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Self sast-scan
        uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: python,bash
      - name: Upload scan reports
        uses: actions/upload-artifact@v1.0.0
        with:
          name: sast-scan-reports
          path: reports
